# Generated by Django 3.2.4 on 2021-06-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('categoryDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolistapp.details')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200)),
                ('taskCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolistapp.category')),
            ],
        ),
    ]
