# Generated by Django 3.2.4 on 2021-06-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_category_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskUser',
            field=models.ForeignKey(default=-78, on_delete=django.db.models.deletion.CASCADE, to='todolistapp.details'),
            preserve_default=False,
        ),
    ]
